### ISSUE TITLE
'NoneType' object has no attribute 'get' in core.py line 120

### ISSUE THREAD

**Issue by RafayelGardishyan** [richelbilderbeek/soto_project#3]
I get this error when I launch main.py in cmd as "python main.py configuration_file.ini"

```
Start Tracking
Warning: unable to open video source:  /media/3f_1.mp4
Warning: unable to open video source:  synth
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    main(['config.ini'])
  File "main.py", line 22, in main
    detector.run()
  File "C:\Users\R\DJOG\soto_project\Tracker\core.py", line 467, in run
    self._init_video_writer(video_file)
  File "C:\Users\R\DJOG\soto_project\Tracker\core.py", line 120, in _init_video_writer
    self.total_number_frames = int(self.camera.get(cv2.cv.CV_CAP_PROP_FRAME_COUNT))
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by richelbilderbeek** [comment]
> Warning: unable to open video source:  /media/3f_1.mp4

The warning is IMHO rather clear: it cannot find the video

**Comment by richelbilderbeek** [comment]
Guess this can be closed...
