### ISSUE TITLE
AttributeError: 'module' object has no attribute 'FastFeatureDetector'

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/soto_project#4]
```
./run
```

results in

```
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    main(['config.ini'])
  File "main.py", line 20, in main
    detector = core.Detector(config)
  File "/home/richel/GitHubs/soto_project/Tracker/core.py", line 70, in __init__
    self.fast = cv2.FastFeatureDetector(**self.FAST_settings)
AttributeError: 'module' object has no attribute 'FastFeatureDetector'
```

**Comment by richelbilderbeek** [comment]
Minimal reproducible example:

```
import cv2
fast = cv2.FastFeatureDetector()
```

**Comment by richelbilderbeek** [comment]
Get all the attributes `cv2` does have:

```
import cv2
dir(module)
```

**Comment by RafayelGardishyan** [comment]
You've installed the newest version of openCV, but you should install version 2.4...

**Comment by richelbilderbeek** [comment]
Using `dir(module)` I get:

```
ER_FMT_CSV', 'FORMATTER_FMT_DEFAULT', 'FORMATTER_FMT_MATLAB', 'FORMATTER_FMT_NUMPY', 'FORMATTER_FMT_PYTHON', 'FarnebackOpticalFlow_create', 'FastFeatureDetector_FAST_N', 'FastFeatureDetector_NONMAX_SUPPRESSION', 'FastFeatureDetector_THRESHOLD', 'FastFeatureDetector_TYPE_5_8', 'FastFeatureDetector_TYPE_7_12', 'FastFeatureDetector_TYPE_9_16', 'FastFeatureDetector_create', 'FileNode', 'FileNode_EMPTY', 'FileNode_FLOAT', 'FileNode_FLOW', 'FileNode_INT', 'FileNode_MAP', 'FileNode_
```

**Comment by richelbilderbeek** [comment]
Hmmm, OpenCV 2.4 is obsoleted in my Lubuntu distro

```
Requirement already satisfied: scipy in /usr/local/lib/python2.7/dist-packages
Collecting opencv-python==2.4
  Could not find a version that satisfies the requirement opencv-python==2.4 (from versions: 3.1.0.0, 3.1.0.1, 3.1.0.2, 3.1.0.3, 3.1.0.4, 3.1.0.5, 3.2.0.6, 3.2.0.7, 3.2.0.8, 3.3.0.9, 3.3.0.10)
No matching distribution found for opencv-python==2.4
```

**Comment by richelbilderbeek** [comment]
I am going to switch on my system's hostname.

```
import socket
socket.gethostname()
```

**Comment by richelbilderbeek** [comment]
Added:

```
        if socket.gethostname() == "lubuntu":
            print("Hey, Richel's computer is detected")
            self.fast = cv2.FastFeatureDetector_create(**self.FAST_settings)
        else:
            print("Use OpenCV 2.4's version")
            self.fast = cv2.FastFeatureDetector(**self.FAST_settings)
```

Solved!
